### PR TITLE
Add National Land Survey of Finland to maps

### PR DESCRIPTION
**Pull request by mudyc**

### CODE REVIEW

**Comment by opoto** [comment]
Thanks a lot @mudyc for this new pull request. However I am reluctant to add new national maps now because I don't want the list of maps to be too long. I think it already reached it's max acceptable by users.

There are 2 ways to handle this limitation:

- I already implemented a way to add your own personal maps in Settings / Personal background maps. This way you can already use your map.
image

- I would like to have a way to configure the list of displayed maps in the selector. By default only the worldwide maps would be visible, and a "settings" button would allow to define the one to view. If you want to contribute on this feature, you are very welcome!

In the meantime what I can propose is to remove the previous map you added, and put this one instead, which looks better. The list would then keep the same size :) If you're ok with this you can update your pull request accordingly.

Thanks again for your interest in WTracks

**Comment by mudyc** [comment]
Yes I see your point. However, it took me 30 minutes to get the map parameters right so I doubt any non-techie is going to use that feature. Well, to discuss the issue further I would put "Map manager" (= selectable list of maps) in settings and show less maps in the default list. Then user can add or remove maps from the list freely. For example I am not interested in FR or SP maps and also many of those biking maps look redundant. Of course the list can have info or link to open this map manager.

Btw. is there somewhere in the settings flag for this ( defaultLengthUnit = window.navigator.language === "en-US") because of that's horrible piece of code. It is assuming location based on language.

**Comment by opoto** [comment]
I agree with your proposal for the map manager. This would be a good improvement.

Regarding the units, default is using the locale, but you can manually switch between metrics and imperial units by clicking on the bottom left scale. I agree it is not clear enough.

**Comment by mudyc** [comment]
Hey nice, thanks :smile: 
Ok let the pull request be open and I will do simple map manager since I need the map for my route design purposes.

**Comment by opoto** [comment]
I eventually added your map and a richer map configuration tool, accessible via the "More..." link in the map selector:
image

**Pull request closed without merging**
